@startuml DAO
abstract class Dao<T> {

    {abstract} + dataSource : DataSource 
    {abstract} + insert() : void 
    {abstract} + retrieve(id : Object) : T 
    {abstract} + retrieveAll() : List<T> 
    {abstract} + update(updated : T) : void 
    {abstract} + delete(id : Object) : void 
    {abstract} + mapResultSet(resultSet : ResultSet) : T 
    + executeSQL(sql : String, mapper : Mapper<T>) : List<T>
} 


class TalkDao<Talk> extends Dao 

class ConferenceDao<Conference> extends Dao

class Day<Day> extends Dao

class Timeslot<Timeslot> extends Dao

@enduml