@startuml Database

    object talk {
        id : UUID 
        title : VARCHAR 
        description : VARCHAR 
        topic_title : VARCHAR 
    }

    object timeslot {
        id : UUID
        start_time : time 
        end_time : time 
        talk_id : UUID 
    }

    object conference {
        id : UUID 
        name : VARCHAR
    }

    object day {
        id : UUID 
        date : date 
    }

    object timeslot_day {
        timeslot_id : UUID 
        day_ID : UUID 
    }


    object conference_day {
        conference_id : UUID 
        day_id : UUID 
    }

    day "1" .. "*" timeslot_day
    timeslot "1"  .. "*" timeslot_day

    conference "1" .. "*" conference_day
    day "1"        .. "*" conference_day
    
    timeslot .. "1" talk
@enduml